baseURL = "https://leafshi1.github.io/my-blog/"
title = "我的 Hugo 博客"
canonifyURLs = true
relativeURLs = true

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"
    version = "v2.6.0"

