baseURL = "https://LeafShi.github.io/my-hugo-blog/"
languageCode = "en-us"
title = "我的 Hugo 博客"
theme = "hugo-theme-stack-master"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack"
